# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/udit01/files/code/vision/scratches

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/udit01/files/code/vision/scratches

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/udit01/files/code/vision/scratches/CMakeFiles /media/udit01/files/code/vision/scratches/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/udit01/files/code/vision/scratches/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named version.out

# Build rule for target.
version.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version.out
.PHONY : version.out

# fast build rule for target.
version.out/fast:
	$(MAKE) -f CMakeFiles/version.out.dir/build.make CMakeFiles/version.out.dir/build
.PHONY : version.out/fast

#=============================================================================
# Target rules for targets named simple.out

# Build rule for target.
simple.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple.out
.PHONY : simple.out

# fast build rule for target.
simple.out/fast:
	$(MAKE) -f CMakeFiles/simple.out.dir/build.make CMakeFiles/simple.out.dir/build
.PHONY : simple.out/fast

#=============================================================================
# Target rules for targets named read.out

# Build rule for target.
read.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read.out
.PHONY : read.out

# fast build rule for target.
read.out/fast:
	$(MAKE) -f CMakeFiles/read.out.dir/build.make CMakeFiles/read.out.dir/build
.PHONY : read.out/fast

#=============================================================================
# Target rules for targets named bgrTg.out

# Build rule for target.
bgrTg.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bgrTg.out
.PHONY : bgrTg.out

# fast build rule for target.
bgrTg.out/fast:
	$(MAKE) -f CMakeFiles/bgrTg.out.dir/build.make CMakeFiles/bgrTg.out.dir/build
.PHONY : bgrTg.out/fast

bgrToGray.o: bgrToGray.cpp.o

.PHONY : bgrToGray.o

# target to build an object file
bgrToGray.cpp.o:
	$(MAKE) -f CMakeFiles/bgrTg.out.dir/build.make CMakeFiles/bgrTg.out.dir/bgrToGray.cpp.o
.PHONY : bgrToGray.cpp.o

bgrToGray.i: bgrToGray.cpp.i

.PHONY : bgrToGray.i

# target to preprocess a source file
bgrToGray.cpp.i:
	$(MAKE) -f CMakeFiles/bgrTg.out.dir/build.make CMakeFiles/bgrTg.out.dir/bgrToGray.cpp.i
.PHONY : bgrToGray.cpp.i

bgrToGray.s: bgrToGray.cpp.s

.PHONY : bgrToGray.s

# target to generate assembly for a file
bgrToGray.cpp.s:
	$(MAKE) -f CMakeFiles/bgrTg.out.dir/build.make CMakeFiles/bgrTg.out.dir/bgrToGray.cpp.s
.PHONY : bgrToGray.cpp.s

imreading.o: imreading.cpp.o

.PHONY : imreading.o

# target to build an object file
imreading.cpp.o:
	$(MAKE) -f CMakeFiles/read.out.dir/build.make CMakeFiles/read.out.dir/imreading.cpp.o
.PHONY : imreading.cpp.o

imreading.i: imreading.cpp.i

.PHONY : imreading.i

# target to preprocess a source file
imreading.cpp.i:
	$(MAKE) -f CMakeFiles/read.out.dir/build.make CMakeFiles/read.out.dir/imreading.cpp.i
.PHONY : imreading.cpp.i

imreading.s: imreading.cpp.s

.PHONY : imreading.s

# target to generate assembly for a file
imreading.cpp.s:
	$(MAKE) -f CMakeFiles/read.out.dir/build.make CMakeFiles/read.out.dir/imreading.cpp.s
.PHONY : imreading.cpp.s

simple.o: simple.cpp.o

.PHONY : simple.o

# target to build an object file
simple.cpp.o:
	$(MAKE) -f CMakeFiles/simple.out.dir/build.make CMakeFiles/simple.out.dir/simple.cpp.o
.PHONY : simple.cpp.o

simple.i: simple.cpp.i

.PHONY : simple.i

# target to preprocess a source file
simple.cpp.i:
	$(MAKE) -f CMakeFiles/simple.out.dir/build.make CMakeFiles/simple.out.dir/simple.cpp.i
.PHONY : simple.cpp.i

simple.s: simple.cpp.s

.PHONY : simple.s

# target to generate assembly for a file
simple.cpp.s:
	$(MAKE) -f CMakeFiles/simple.out.dir/build.make CMakeFiles/simple.out.dir/simple.cpp.s
.PHONY : simple.cpp.s

version.o: version.cpp.o

.PHONY : version.o

# target to build an object file
version.cpp.o:
	$(MAKE) -f CMakeFiles/version.out.dir/build.make CMakeFiles/version.out.dir/version.cpp.o
.PHONY : version.cpp.o

version.i: version.cpp.i

.PHONY : version.i

# target to preprocess a source file
version.cpp.i:
	$(MAKE) -f CMakeFiles/version.out.dir/build.make CMakeFiles/version.out.dir/version.cpp.i
.PHONY : version.cpp.i

version.s: version.cpp.s

.PHONY : version.s

# target to generate assembly for a file
version.cpp.s:
	$(MAKE) -f CMakeFiles/version.out.dir/build.make CMakeFiles/version.out.dir/version.cpp.s
.PHONY : version.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... version.out"
	@echo "... simple.out"
	@echo "... read.out"
	@echo "... bgrTg.out"
	@echo "... bgrToGray.o"
	@echo "... bgrToGray.i"
	@echo "... bgrToGray.s"
	@echo "... imreading.o"
	@echo "... imreading.i"
	@echo "... imreading.s"
	@echo "... simple.o"
	@echo "... simple.i"
	@echo "... simple.s"
	@echo "... version.o"
	@echo "... version.i"
	@echo "... version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

